# Generated by Django 5.2.2 on 2025-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringdonation',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
