# Generated by Django 5.2.2 on 2025-06-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_recurringdonation_paystack_subscription_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringdonation',
            name='campaign_id',
        ),
    ]
