# Generated by Django 5.2.2 on 2025-06-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_campaign_our_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='our_story',
        ),
    ]
