# Generated by Django 5.2.2 on 2025-06-12 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_campaign_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
