# Generated by Django 5.2.2 on 2025-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_remove_campaign_campaign_id_alter_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
