# Generated by Django 5.2.2 on 2025-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_campaign_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='team_needs',
            field=models.JSONField(default=list),
        ),
    ]
