# Generated by Django 5.2.2 on 2025-06-12 20:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_campaign_team_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='manual_total_raised',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial raised amount before donations were tracked', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
