# Generated by Django 5.2.2 on 2025-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_campaign_manual_total_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide campaign from public view'),
        ),
    ]
