# Generated by Django 5.2.2 on 2025-06-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_campaign_completed_at_campaign_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
